//! Nix-produced fleet JSON contract test.
//!
//! Skipped unless the `CONSORTIUM_FLEET_CONFIG` env var points at the JSON
//! file generated by the Nix check `checks.fleet-contract` (real `mkFleet`
//! evaluation of `nix/lib/fleet-contract-fixture.nix`). The Nix gate runs:
//!
//! ```text
//! cargo test -p consortium-integration \
//!   --test nix_fleet_contract -- --ignored
//! ```

use consortium_integration::fleet::{FleetConfig, ProfileType};
use std::path::PathBuf;

fn load_fleet_config() -> FleetConfig {
    let path = std::env::var("CONSORTIUM_FLEET_CONFIG").expect(
        "CONSORTIUM_FLEET_CONFIG must point at the mkFleet-generated JSON \
         (set by the Nix checks.fleet-contract gate)",
    );
    FleetConfig::from_file(&PathBuf::from(path)).expect("Nix-generated fleet JSON must parse")
}

#[test]
#[ignore = "requires CONSORTIUM_FLEET_CONFIG from the Nix fleet-contract gate"]
fn nix_fleet_json_has_non_default_flake_uri() {
    let config = load_fleet_config();
    assert_eq!(
        config.flake_uri, "github:example/fleet-contract",
        "mkFleet must emit the agreed non-default flakeUri"
    );
}

#[test]
#[ignore = "requires CONSORTIUM_FLEET_CONFIG from the Nix fleet-contract gate"]
fn nix_fleet_json_node_matches_fixture() {
    let config = load_fleet_config();
    assert_eq!(
        config.nodes.len(),
        1,
        "contract fixture defines exactly one node"
    );
    let node = &config.nodes["contract-01"];
    assert_eq!(node.name, "contract-01");
    assert_eq!(node.target_host, "10.99.0.42");
    assert_eq!(node.target_user, "root");
    assert_eq!(node.target_port, None);
    assert_eq!(node.system, "x86_64-linux");
    assert_eq!(node.profile_type, ProfileType::Nixos);
    assert!(!node.build_on_target);
    assert_eq!(node.tags, vec!["contract".to_string()]);
    assert_eq!(node.drv_path, None, "mkFleet strips drv_path before toJSON");
}

#[test]
#[ignore = "requires CONSORTIUM_FLEET_CONFIG from the Nix fleet-contract gate"]
fn nix_fleet_json_integration_configs_match_fixture() {
    let config = load_fleet_config();
    let ansible = config
        .ansible_config
        .as_ref()
        .expect("contract fixture includes ansibleConfig");
    assert_eq!(ansible.control_node, "contract-ctl.example.internal");

    let slurm = config
        .slurm_config
        .as_ref()
        .expect("contract fixture includes slurmConfig");
    assert_eq!(slurm.submit_node, "contract-submit.example.internal");
    assert_eq!(slurm.submit_user, "root");
    assert_eq!(slurm.control_node, "contract-ctl.example.internal");

    let ray = config
        .ray_config
        .as_ref()
        .expect("contract fixture includes rayConfig");
    assert_eq!(ray.head_address, "contract-head.example.internal:8787");

    let skypilot = config
        .skypilot_config
        .as_ref()
        .expect("contract fixture includes skypilotConfig");
    assert_eq!(skypilot.cloud, "aws");
}
