//! The generic contract checks.
//!
//! Each `#[test]` generated by
//! [`integration_contract_tests!`](crate::integration_contract_tests)
//! delegates to one function here. Integration authors normally never call
//! these directly; they are public so the macro (expanded in the
//! integration's crate) can reach them, and so meta-tests can assert that
//! broken implementations are caught.

use std::sync::Arc;

use consortium_integration::exec::{ExecOutput, ScriptedExecutor};
use consortium_integration::report::IntegrationReport;

use crate::{Contract, Phase};

/// Validate the static invariants of a phase declaration and return it.
///
/// Panics with a message naming the integration when: no phases are
/// declared, a phase name is duplicated, a marker is empty, two markers
/// overlap (substring relation), or an `after` edge does not name an
/// *earlier* phase.
fn validated_phases<C: Contract>() -> Vec<Phase> {
    let phases = C::phases();
    assert!(
        !phases.is_empty(),
        "{}: phases() must declare at least one phase",
        C::name()
    );
    for (i, phase) in phases.iter().enumerate() {
        assert!(
            !phase.marker.trim().is_empty(),
            "{}: phase '{}' has an empty marker",
            C::name(),
            phase.name
        );
        for earlier in &phases[..i] {
            assert_ne!(
                earlier.name,
                phase.name,
                "{}: duplicate phase name '{}'",
                C::name(),
                phase.name
            );
            assert!(
                !phase.marker.contains(earlier.marker) && !earlier.marker.contains(phase.marker),
                "{}: markers {:?} (phase '{}') and {:?} (phase '{}') overlap; markers must be \
                 mutually non-substring so failure scripting hits exactly one phase",
                C::name(),
                earlier.marker,
                earlier.name,
                phase.marker,
                phase.name
            );
        }
        for dep in phase.after {
            assert!(
                phases[..i].iter().any(|p| p.name == *dep),
                "{}: phase '{}' declares after={:?}; `after` must name a phase declared \
                 earlier in phases() (declaration order must be topological)",
                C::name(),
                phase.name,
                dep
            );
        }
    }
    phases
}

/// The one tolerated failure semantic: `run` either returns `Err(..)`, or
/// returns `Ok(report)` with `report.is_success() == false` and
/// `report.failure_count() >= 1`.
fn assert_failure_outcome<C: Contract>(outcome: &Result<C::Report, C::Error>, scenario: &str) {
    match outcome {
        // Error-return convention: nothing further to check.
        Err(_) => {}
        Ok(report) => {
            assert!(
                !report.is_success(),
                "{}: {}: run returned Ok with a successful report; a failure scenario must \
                 produce Err(..) or a report with is_success() == false",
                C::name(),
                scenario
            );
            assert!(
                report.failure_count() >= 1,
                "{}: {}: report is not successful but failure_count() is 0; a failure \
                 scenario must attribute at least one failure",
                C::name(),
                scenario
            );
        }
    }
}

/// `run(config_missing(), ..)` must return `Err` before issuing any command.
pub fn missing_config_errors<C: Contract>() {
    // Catch-all permissive executor: if the integration *did* try to run
    // something it would succeed — so a pass here cannot be an accident of
    // scripting.
    let exec = Arc::new(ScriptedExecutor::new().on("", ExecOutput::ok("")));
    let outcome = C::run(&C::config_missing(), exec.clone(), &C::Options::default());
    let summary = outcome.as_ref().map(|r| {
        format!(
            "Ok(report: is_success={}, failures={}, successes={})",
            r.is_success(),
            r.failure_count(),
            r.success_count()
        )
    });
    assert!(
        outcome.is_err(),
        "{}: run() with a config missing this integration's sub-config must return Err; got {}",
        C::name(),
        summary.unwrap_or_else(|_| "Err(..)".to_string())
    );
    assert_eq!(
        exec.invocation_count(),
        0,
        "{}: run() with missing sub-config must fail before issuing any command; \
         invocations: {:?}",
        C::name(),
        exec.invocations()
    );
}

/// Planning must produce descriptions without executing anything.
pub fn plan_has_no_side_effects<C: Contract>() {
    // No rules: any actual exec call would fail with `Unexpected` — and,
    // crucially, would be *recorded*.
    let exec = Arc::new(ScriptedExecutor::new());
    let descriptions = C::task_descriptions(&C::config_complete(), exec.clone());
    assert!(
        !descriptions.is_empty(),
        "{}: task_descriptions() returned no tasks for the complete config",
        C::name()
    );
    for desc in &descriptions {
        assert!(
            !desc.trim().is_empty(),
            "{}: task_descriptions() returned an empty or whitespace-only description",
            C::name()
        );
        assert!(
            !desc.chars().any(char::is_control),
            "{}: task description {:?} contains control characters; descriptions must be \
             single-line printable text",
            C::name(),
            desc
        );
    }
    assert_eq!(
        exec.invocation_count(),
        0,
        "{}: task_descriptions() must be side-effect free, but it executed commands: {:?}",
        C::name(),
        exec.invocations()
    );
}

/// With the happy executor the run succeeds, every phase is invoked, and
/// declared `after` edges hold in the recorded invocation order.
pub fn happy_path<C: Contract>() {
    let phases = validated_phases::<C>();
    let exec = Arc::new(C::happy_executor());
    let outcome = C::run(&C::config_complete(), exec.clone(), &C::Options::default());
    let report = outcome.unwrap_or_else(|err| {
        panic!(
            "{}: happy-path run returned Err({:?}); with happy_executor() every scripted \
             command succeeds",
            C::name(),
            err
        )
    });
    let invocations = exec.invocations();
    assert!(
        report.is_success(),
        "{}: happy-path report must be successful; failure_count() = {}.\ninvocations: {:#?}",
        C::name(),
        report.failure_count(),
        invocations
    );
    assert_eq!(
        report.failure_count(),
        0,
        "{}: happy-path report must have zero failures; failure_count() = {}",
        C::name(),
        report.failure_count()
    );
    for phase in &phases {
        assert!(
            invocations.iter().any(|cmd| cmd.contains(phase.marker)),
            "{}: happy path: phase '{}' was never invoked (marker {:?} not found).\n\
             invocations: {:#?}",
            C::name(),
            phase.name,
            phase.marker,
            invocations
        );
    }
    for phase in &phases {
        for dep_name in phase.after {
            let dep = phases
                .iter()
                .find(|p| p.name == *dep_name)
                .expect("phase graph was validated");
            let dep_idx = exec
                .invocation_index_containing(dep.marker)
                .expect("dependency phase was asserted invoked above");
            let phase_idx = exec
                .invocation_index_containing(phase.marker)
                .expect("phase was asserted invoked above");
            assert!(
                dep_idx < phase_idx,
                "{}: happy path: ordering violated — phase '{}' (marker {:?}, first invoked \
                 at #{}) must come after phase '{}' (marker {:?}, first invoked at #{})",
                C::name(),
                phase.name,
                phase.marker,
                phase_idx,
                dep.name,
                dep.marker,
                dep_idx
            );
        }
    }
}

/// When the first phase fails, the pipeline aborts: no later phase's marker
/// is ever invoked.
pub fn first_phase_failure_aborts_pipeline<C: Contract>() {
    let phases = validated_phases::<C>();
    let first = &phases[0];
    let exec = Arc::new(C::executor_failing_phase(first.marker));
    let outcome = C::run(&C::config_complete(), exec.clone(), &C::Options::default());
    assert_failure_outcome::<C>(&outcome, "first-phase failure");
    let invocations = exec.invocations();
    assert!(
        invocations.iter().any(|cmd| cmd.contains(first.marker)),
        "{}: first-phase failure: phase '{}' (marker {:?}) was never even attempted.\n\
         invocations: {:#?}",
        C::name(),
        first.name,
        first.marker,
        invocations
    );
    for later in &phases[1..] {
        assert!(
            !invocations.iter().any(|cmd| cmd.contains(later.marker)),
            "{}: first-phase failure: phase '{}' (marker {:?}) must never run after phase \
             '{}' failed, but it was invoked.\ninvocations: {:#?}",
            C::name(),
            later.name,
            later.marker,
            first.name,
            invocations
        );
    }
    if let Ok(report) = &outcome {
        assert_eq!(
            report.success_count(),
            0,
            "{}: first-phase failure: no unit of work may succeed when the first phase \
             fails for every host; success_count() = {}",
            C::name(),
            report.success_count()
        );
    }
}

/// When a mid-pipeline phase fails, every phase after it is cancelled while
/// at least one earlier phase ran.
pub fn mid_pipeline_failure_cancels_dependents<C: Contract>() {
    let phases = validated_phases::<C>();
    if phases.len() < 2 {
        eprintln!(
            "{}: mid-pipeline failure check needs at least 2 phases, found {}; skipping",
            C::name(),
            phases.len()
        );
        return;
    }
    let mid = phases.len() / 2;
    let failing = &phases[mid];
    let exec = Arc::new(C::executor_failing_phase(failing.marker));
    let outcome = C::run(&C::config_complete(), exec.clone(), &C::Options::default());
    assert_failure_outcome::<C>(&outcome, "mid-pipeline failure");
    let invocations = exec.invocations();
    for later in &phases[mid + 1..] {
        assert!(
            !invocations.iter().any(|cmd| cmd.contains(later.marker)),
            "{}: mid-pipeline failure: phase '{}' (marker {:?}) must never run after phase \
             '{}' failed.\ninvocations: {:#?}",
            C::name(),
            later.name,
            later.marker,
            failing.name,
            invocations
        );
    }
    let any_before = phases[..mid]
        .iter()
        .any(|p| invocations.iter().any(|cmd| cmd.contains(p.marker)));
    assert!(
        any_before,
        "{}: mid-pipeline failure: expected at least one phase before '{}' (marker {:?}) to \
         have been invoked.\ninvocations: {:#?}",
        C::name(),
        failing.name,
        failing.marker,
        invocations
    );
}

/// With the partial-failure fixture, the surviving host completes every
/// phase while the failed host never reaches the blocked phase.
pub fn partial_host_failure_continues_independents<C: Contract>() {
    let Some(partial) = C::partial_failure() else {
        eprintln!(
            "{}: partial_failure() returned None; skipping per-host partial-failure check",
            C::name()
        );
        return;
    };
    let exec = Arc::new(partial.executor);
    let outcome = C::run(&C::config_complete(), exec.clone(), &C::Options::default());
    assert_failure_outcome::<C>(&outcome, "partial host failure");
    let invocations = exec.invocations();
    for phase in &C::phases() {
        let survived = invocations
            .iter()
            .any(|cmd| cmd.contains(phase.marker) && cmd.contains(partial.surviving_host_marker));
        assert!(
            survived,
            "{}: partial host failure: surviving host must complete phase '{}' — need an \
             invocation containing both {:?} (phase marker) and {:?} (surviving host \
             marker).\ninvocations: {:#?}",
            C::name(),
            phase.name,
            phase.marker,
            partial.surviving_host_marker,
            invocations
        );
    }
    assert!(
        !invocations.iter().any(|cmd| {
            cmd.contains(partial.blocked_phase_marker) && cmd.contains(partial.failed_host_marker)
        }),
        "{}: partial host failure: blocked phase marker {:?} must never run for the failed \
         host {:?}.\ninvocations: {:#?}",
        C::name(),
        partial.blocked_phase_marker,
        partial.failed_host_marker,
        invocations
    );
    if let Ok(report) = &outcome {
        assert!(
            report.success_count() >= 1 && report.failure_count() >= 1,
            "{}: partial host failure: report must show both successes (surviving host) and \
             failures (failed host); success_count() = {}, failure_count() = {}",
            C::name(),
            report.success_count(),
            report.failure_count()
        );
    }
}

/// Each declared option variant skips exactly its declared phases and
/// otherwise succeeds.
pub fn option_variants_skip_declared_phases<C: Contract>() {
    let phases = validated_phases::<C>();
    let variants = C::option_variants();
    if variants.is_empty() {
        eprintln!(
            "{}: option_variants() is empty; skipping option-variant check",
            C::name()
        );
        return;
    }
    for variant in &variants {
        for skipped in &variant.skipped_phases {
            assert!(
                phases.iter().any(|p| p.name == *skipped),
                "{}: option variant '{}' skips unknown phase {:?}; skipped_phases must \
                 contain phase names from phases()",
                C::name(),
                variant.name,
                skipped
            );
        }
        let exec = Arc::new(C::happy_executor());
        let outcome = C::run(&C::config_complete(), exec.clone(), &variant.options);
        let report = outcome.unwrap_or_else(|err| {
            panic!(
                "{}: option variant '{}': run returned Err({:?}) on a happy executor",
                C::name(),
                variant.name,
                err
            )
        });
        assert!(
            report.is_success(),
            "{}: option variant '{}': run must succeed when its skipped phases are omitted; \
             failure_count() = {}",
            C::name(),
            variant.name,
            report.failure_count()
        );
        let invocations = exec.invocations();
        for phase in &phases {
            let invoked = invocations.iter().any(|cmd| cmd.contains(phase.marker));
            if variant.skipped_phases.contains(&phase.name) {
                assert!(
                    !invoked,
                    "{}: option variant '{}': skipped phase '{}' (marker {:?}) was invoked.\n\
                     invocations: {:#?}",
                    C::name(),
                    variant.name,
                    phase.name,
                    phase.marker,
                    invocations
                );
            } else {
                assert!(
                    invoked,
                    "{}: option variant '{}': phase '{}' (marker {:?}) is not skipped and \
                     must run.\ninvocations: {:#?}",
                    C::name(),
                    variant.name,
                    phase.name,
                    phase.marker,
                    invocations
                );
            }
        }
    }
}
